version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t tasksphere-react -f reactapp/Dockerfile reactapp

workflows:
  react-integration:  
    jobs:
      - build-and-test
